# Generated by Django 3.0.6 on 2020-07-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_favourite_comments'),
        ('core', '0006_auto_20200319_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
