# Generated by Django 3.0.6 on 2020-07-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200215_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_comments',
        ),
    ]
